services:
  rag-engine:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rag
    ports:
      - "8002:8001"
    volumes:
      - ..:/app
      - ${APPDATA}/gcloud/application_default_credentials.json:/secrets/gcp-adc.json:ro
    env_file:
    - ../.env.local
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-adc.json



  mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mcp
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    environment:
      - RAG_BASE_URL=http://rag-engine:8001
    depends_on:
      - rag-engine

  streamlit-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    ports:
      - "8501:8501"
    volumes:
      - ..:/app
      - ${APPDATA}/gcloud/application_default_credentials.json:/secrets/gcp-adc.json:ro
    env_file:
      - ../.env.local 
    environment:
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=none
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-adc.json

    depends_on:
      - rag-engine